mirrulations/mirrulations

- mirrulations-work-server/src/mirrserver/work_server.py
The client already logs the file path when sending a job back to the work server. I added a log line to the work-server so that it also outputs the file path of the saved job.
> Make work-server output file path when saving job

- docker-compose.yml
- docs/development.md
- mirrulations-dashboard/src/mirrdash/static/index.js
- mirrulations-dashboard/src/mirrdash/templates/index.html
* Kyle and Evan found that I had used the same key for two clients in deployment. To correct this:
* Client 28 was removed from the docker compose file and the dashboard.
* The documentation now has developers make 27 clients instead of 28.
* Modification to the .env files in the box will need to be done before this change is deployed into production.
> Remove Client28 due to API-Key Repetiton

- mirrulations-client/src/mirrclient/client.py
On line 246 of client.py, the result of retrieving a value from a key from JSON is not being verified. There are instances where `file_info = response_from_related["data"][0]["attributes"]["fileFormats"]` results in None.
If None, raise KeyError, catch, log, return {}
> Add check for None

- docs/attachments.md
Pull Request adds documentation about attachments, including the types of files attachments can be and an idea of what the distribution of file types we will look like.
> Add attachments breakdown file in docs

- docs/client.md
- docs/development.md
- docs/env_files.md
- docs/production.md
- mirrulations-client/src/mirrclient/client.py
- mirrulations-client/tests/test_client.py
Work server no longer assigns client IDs. Client uses ID stored in its respective .env file (ID= ). Removed some of the outdated tests and created a test for the new functionality.
> Remove work server assigning client ID

- docs/development.md
- docs/env_files.md
When looking at the docker-compose logs, we were seeing bursts of log activity.  This was caused because Python was buffering output - from Docker's perspective, there were no logs, and then a large number of lines would arrive in a fraction of a second.
By setting the PYTHONUNBUFFERED environment variable, Python will stop using buffered output, and instead generate output immediately.  This causes the lines to arrive at Docker as soon as they are generated, which makes our logs accurately reflect what is happening in the containers.
> Add discussion of PYTHONUNBUFFERED=TRUE in .env files

- mirrulations-work-server/src/mirrserver/work_server.py
- mirrulations-work-server/tests/test_work_server.py
I removed functions from the work server that involved the old process of getting client IDs from the redis database. This was based on moving the client IDs into the env files instead of having them be processed by the work server from redis. The tests have also been updated in accommodation to the functions in the work server. This is ready to be merged, as the new process of hardcoding client IDs has been implemented and updated in the documentation as well.
> Remove work server functions involving old client ID method

- mirrulations-client/src/mirrclient/client.py
- mirrulations-client/tests/test_client.py
- Refactored perform_attachment_job() in Client.py to not use a try-except block. Refactor checks if the JSON for an attachment is valid, essentially checking if there are any attachments to download. If there aren't attachments, no further steps need to be taken. 
- Also added some mock tests that mimic the handling of TypeError (NoneType) and IndexError
> Attachment Refactor for Client

- dev_setup.py
- docs/development.md
- docs/env_files.md
I made a script that automates various parts of the development setup. This script will create all files necessary in the env_files directory, and makes the ~/data folder as well. It also knows how many clients are currently in the system so that whenever any new ones are added, this script will update accordingly.  The only input this requires is the user's API key, which can be given through running the script through the terminal.
> Make setup script for development

- mirrulations-work-generator/src/mirrgen/results_processor.py
- mirrulations-work-generator/src/mirrgen/work_generator.py
Logging looks like:
```
➜  mirrulations git:(work_gen_logging) ✗ docker-compose logs -ft work_generator
Attaching to mirrulations_work_generator_1
work_generator_1  | 2023-03-02T20:11:00.233280211Z Begin generate docket jobs
work_generator_1  | 2023-03-02T20:11:10.330946300Z Added dockets: 1
work_generator_1  | 2023-03-02T20:11:10.331227175Z End generate docket jobs
work_generator_1  | 2023-03-02T20:11:10.331238966Z Begin generate document jobs
work_generator_1  | 2023-03-02T20:11:16.068664761Z Added documents: 250
work_generator_1  | 2023-03-02T20:11:21.837571763Z Added documents: 250
work_generator_1  | 2023-03-02T20:11:27.557239252Z Added documents: 250
```
> Add basic logging for the work generator

- devup
- docker-compose.yml
- mirrulations-core/setup.cfg
- mirrulations-core/src/mirrcore/job_queue.py
- mirrulations-core/src/mirrcore/rabbitmq.py
- mirrulations-core/tests/test_job_queue.py
- mirrulations-core/tests/test_rabbitmq.py
- mirrulations-dashboard/Dockerfile
- mirrulations-dashboard/src/mirrdash/dashboard_server.py
- mirrulations-dashboard/src/mirrdash/wsgi.py
- mirrulations-dashboard/tests/test_dashboard.py
- mirrulations-mocks/src/mirrmock/mock_rabbitmq.py
- mirrulations-rabbitmq/Dockerfile
- mirrulations-work-generator/tests/test_results_processor.py
- mirrulations-work-generator/tests/test_workgen.py
[https://rabbitmq.com/](https://rabbitmq.com/) is a Message Queue, and it allow us to efficiently manage the jobs waiting.  In the current system we use Redis, which holds all data *in memory.*  As the size of the queue grew, the `capstone` box ran out of memory, and the system crashed.
RabbitMQ is a more appropriate technology for this portion of the system.
> Move jobs_waiting_queue out of Redis and into RabbitMQ

- pylintrc
I noticed this recommendation when running static analysis. The prompt should be fixed now.
Before:
```
flake8 mirrulations-client mirrulations-dashboard mirrulations-work-generator mirrulations-work-server;
pycodestyle mirrulations-client mirrulations-dashboard mirrulations-work-generator mirrulations-work-server;
pylint mirrulations-client mirrulations-dashboard mirrulations-work-generator mirrulations-work-server;
pylint: Command line or configuration file:1: UserWarning: Specifying exception names in the overgeneral-exceptions option without module name is deprecated and support for it will be removed in pylint 3.0. Use fully qualified name (maybe 'builtins.BaseException' ?) instead.
pylint: Command line or configuration file:1: UserWarning: Specifying exception names in the …
```
> Fix pylint static analysis recommendation

- dev_setup.py
- docs/development.md
- install_packages.sh
I added a shell script to do all necessary pip installs of the components of the system. I felt this was necessary because the number of packages to install was increasing, and any developer would have to  manually do each one. The script will check if a python virtual environment exists, and make it if needed before using pip to do all package installations.
> Add script to install packages

- mirrulations-core/src/mirrcore/path_generator.py
This removes two output statements when we have to parse a docket it. This output isn't necessary, and it clutters the logs.
> Reduce PathGenerator output.

- mirrulations-mocks/src/mirrmock/mock_dataset.py
- mirrulations-work-generator/src/mirrgen/results_processor.py
- mirrulations-work-generator/src/mirrgen/work_generator.py
- mirrulations-work-generator/tests/test_results_processor.py
- mirrulations-work-generator/tests/test_workgen.py
The work generator checks to see if the data exists before it adds it to the queue.  Previously, this looked at Mongo, which was taking .5 to 1.5 seconds per check.  This made the work generation process too slow - many clients were sitting idle.
This change uses the PathGenerator to compute the path of the resulting file.  Because search results have id, agency, etc., they are close enough that the PathGenerator can compute the path (with a small hack).
This method also allowed us to get rid of the DataStorage class in the work generation process.  This simplifies the interface to these objects in production and in testing.
> make the work generator look for duplication on disk instead of mongo.

- mirrulations-core/src/mirrcore/path_generator.py
- mirrulations-core/tests/test_path_generator.py
Work_generator logs were being cluttered so I removed a print statement coming from the path_generator regarding parsing
> Remove print statement from path_generator

- mirrulations-extractor/src/mirrextractor/extractor.py
This will help prevent the extractor from crashing.
> broader except when saving pdf

- docker-compose.yml
The start_period addition to the docker compose file will give mongo time to spin up and load the data before the health check begins. I may help keep the container healthy, but the time will need some adjustment.
> Add start_period to give Mongo time to spin up

- docker-compose.yml
- mirrulations-validation/src/mirrval/job_validator.py
I moved the validator to save the missing jobs in a json file. Originally, it was saving the file within the system itself, but now it will save to the data folder along with all downloaded and extracted data.
> Move data validator save path for missing jobs

- docker-compose.yml
- mirrulations-validation/src/mirrval/job_validator.py
We realized that the if the validator gets shut down in the middle of it's process, it will duplicate jobs that already exist in the missing_jobs JSON file. To solve this, I have the validator check the file to see if those jobs are in there, and those jobs will not be rewritten if they are in the file already.
This is not ready to be merged until we make a soft link in the data folder.
> Check for missing jobs in validator JSON file before writing to it

- mirrulations-core/src/mirrcore/redis_check.py
- mirrulations-core/tests/test_is_redis_available.py
- mirrulations-validation/src/mirrval/job_validator.py
- mirrulations-work-generator/src/mirrgen/work_generator.py
- mirrulations-work-server/src/mirrserver/wsgi.py
Code to load Redis is duplicated in several (3 different) packages:
[mirrulations-validation/src/mirrval/job_validator.py](https://github.com/MoravianUniversity/mirrulations/blob/f822001c8cffef74d74b0a8b497832fd066946a0/mirrulations-validation/src/mirrval/job_validator.py)
[mirrulations-work-generator/src/mirrgen/work_generator.py](https://github.com/MoravianUniversity/mirrulations/blob/fd73db0a6fcf951f35d08e457ece2548beed8f46/mirrulations-work-generator/src/mirrgen/work_generator.py)
[mirrulations-work-server/src/mirrserver/wsgi.py](https://github.com/MoravianUniversity/mirrulations/blob/3a4331b8fdab41a12f33c4e0e14bb9bf4de4caa8/mirrulations-work-server/src/mirrserver/wsgi.py)
> Refactor Duplicate Code for Loading Redis

- mirrulations-extractor/src/mirrextractor/extractor.py
- mirrulations-extractor/tests/test_extractor.py
Pdfminer.six threw an error when extracting text from a PDF.
It was an internal error and out of our control. The only way afaik to fix this is to flatten the PDF followed by OCR.
> Text extraction error handling

- mirrulations-client/src/mirrclient/client.py
- mirrulations-client/tests/test_client.py
- mirrulations-core/src/mirrcore/jobs_statistics.py
- mirrulations-dashboard/src/mirrdash/dashboard_server.py
- mirrulations-dashboard/src/mirrdash/wsgi.py
- mirrulations-dashboard/tests/test_dashboard.py
- mirrulations-mocks/src/mirrmock/mock_job_statistics.py
- mirrulations-work-server/src/mirrserver/work_server.py
- mirrulations-work-server/tests/test_work_server.py
Made a class for the job done statistics that saves jobs done counts to Redis.
Dashboard accesses the JobStatistics class to get counts. Removed Mongo usage from Dashboard
Client uses the JobStatistics class to update the counts
> Redis to get jobs done counts instead of Mongo

- mirrulations-extractor/src/mirrextractor/extractor.py
Another fix for the text extraction due to unforeseen corrupt pdfs.
> add catch for TypeError when using high_level extract

- mirrulations-core/src/mirrcore/extraction_queue.py
This disable is unneeded in the file. It seems like it can be removed.
> Remove pylint disable from extraction_queue.py

- docker-compose.yml
This should keep the dashboard and work-generator from crashing when mongo crashes.
> Remove depends_on mongo from work-generator and dashboard

- mirrulations-client/src/mirrclient/saver.py
- mirrulations-client/tests/test_saver.py
* S3 was saving the full data dictionary, not just the JSON result
* This problem should be fixed when we do the next S3 sync
* data["results"] is the correct json result
* Just data includes keys "job_id", "job_type", "results"
> Corrects issue with saving full data dict to S3

- .github/actions/setup_environment/action.yml
I noticed that the validator package was not included in the github actions file. It added the line to include the package.
> Add validator package to the github actions file

- mirrulations-dashboard/src/mirrdash/static/index.js
The javascript file for the dashboard's front end was updated to remove Mongo and Work_server updateStatus() calls
> Remove Mongo and Work_Server from javascript

- docker-compose.yml
- mirrulations-validation/src/mirrval/job_validator.py
I removed the need for the DataStorage class in the Validator. This was a needed change because it was the last place in the system using Mongo. I instead used the PathGenerator to check if the path for the downloaded file exists before writing to the missing jobs file.
> Remove Mongo in Validator

- dev_setup.py
This will add the creation of the extractor.env file to the env_files folder in the dev setup script. This was necessary because running devup would not work because it would expect extractor.env if it wasn't manually created.
> Add extractor env file to dev script

- mirrulations-dashboard/src/mirrdash/static/index.js
the estimated number of attachments wasn't added to the denominator of the corpus calculation. Updated javascript to include it
> update to corpus calculation

- mirrulations-core/src/mirrcore/data_counts.py
- mirrulations-work-generator/src/mirrgen/work_generator.py
Handle exceptional cases when getting the data counts from Regulations.gov. 
DataCounts class raises a DataNotFoundException when Regulations.gov does not return the expected data. 
The work generator catches this exception and prints out a message.
> Data not found exception

- docker-compose.yml
Add the env file that contains the AWS credentials.
Also, remove restart for now.  If the extractor fails on a pdf file it will try the same pdf after restart and fail again.  This will likely cause a resource leak over time.
> add env file and remove restart

- mirrulations-extractor/src/mirrextractor/extractor.py
- mirrulations-extractor/tests/test_extractor.py
Some pdfs are generating a struct.error when extracting text.  This fix catches the error, logs it, and then moves on.
> handle struct.error exception

- mirrulations-extractor/src/mirrextractor/extractor.py
- mirrulations-extractor/tests/test_extractor.py
If a file contains a password, we skip it.
For future reference, this is an example of a file with a password: `/data/data/AMS/AMS-SC-19-0042/binary-AMS-SC-19-0042/comments_attachments/AMS-SC-19-0042-1782_attachment_1.pdf`
> Handle password on pdf

- docker-compose.yml
Log file size is unbounded by default, and we log a lot of stuff. The "local" setting for logs uses a max file size for the log file, which will limit how much disk space is used by our logs.
All containers are set to use a 10MB log, which should give us plenty of historical data to see what is happening.
> Change logging on all containers to "local."

- docs/dashboard.md
- mirrulations-dashboard/src/mirrdash/dashboard_server.py
- mirrulations-dashboard/src/mirrdash/static/index.js
- mirrulations-dashboard/tests/test_dashboard.py
This PR contains makes the dashboard better reflect the true status of a container. It also better documents the dashboard API by providing examples.
* return the actual container state according to docker
* style running and not running container cards differently
* update documentation/tests
> More Informative Dashboard Container Status
