mirrulations/mirrulations

docker-compose.yml

Made changes to the docker-compose file that restarts redis when it shuts down unexpectedly.

Add redis restart

---

docs/mongo_collections.md

Updated mongo_collections README with a section with steps on how to import a mongo dump onto Mongo running on localhost

Updated mongo_collections README

---

mirrulations-client/src/mirrclient/client.py
mirrulations-work-server/src/mirrserver/work_server.py

I corrected some more typos that I found in the documentation when working on these files.

Fix typos in client.py and work_server.py

---

docs/EC2-Mongo.md

* This file describes the process of connecting to the EC2 instance I created for querying our data away from the production capstone system
* If you have any questions about this process please ask

EC2-Mongo Steps

---

mirrulations-client/src/mirrclient/client.py
mirrulations-work-server/src/mirrserver/work_server.py
mirrulations-work-server/tests/test_work_server.py

This is not ready
- Going to make tests for logs
- also look into the printing of URLs in work_server
- also looking into the success and failure of work_server

Tests for work_server logging 

---

mirrulations-client/src/mirrclient/client.py
mirrulations-client/tests/test_client.py

TODO:
- Creating tests for client logs 
- Add SUCCESS and FAILURE tags to client logs 
- Client logs URL in attachment jobs

Initial commit, testing client logs

---

docker-compose.yml
mirrulations-client/Dockerfile
mirrulations-client/src/mirrclient/client.py
mirrulations-client/tests/test_client.py
mirrulations-mocks/src/mirrmock/mock_data_storage.py
mirrulations-work-server/src/mirrserver/work_server.py
mirrulations-work-server/tests/test_work_server.py

Updated docker-compose.yml to mount shared volume between container and host for writing data.

Write to disk from clients

---

docs/development.md

Added both devup and devdown to development.md, dev_setup.py was actually already mentioned in the last line of the Docker Setup section.

Added Unmentioned Dev Scripts

---

mirrulations-core/src/mirrcore/rabbitmq.py
mirrulations-work-generator/src/mirrgen/work_generator.py
mirrulations-work-server/src/mirrserver/work_server.py
mirrulations-work-server/tests/test_work_server.py

Updated work server to get jobs from Rabbitmq

Work server gets jobs from rabbitmq

---

docker-compose.yml
mirrulations-mongo/Dockerfile

Specify the version numbers for images in the docker-compose.yml file. Prevents versioning issues with these services across production and development environments.

Docker compose image versions

---

mirrulations-work-generator/src/mirrgen/search_iterator.py
mirrulations-work-generator/tests/test_search_traverser.py
mirrulations-work-generator/tests/test_workgen.py

Pull request fixes problem with invalid failure url being outputted from work generator
Fixes:
* API Key exposure in logs 
* Special Characters in url output

Work Generator Failure Logs

---

mirrulations-dashboard/src/mirrdash/static/style.css
mirrulations-dashboard/src/mirrdash/templates/dev.html
mirrulations-dashboard/src/mirrdash/templates/index.html

visual representation of what the progress to corpus bar will look like. Also added a link in the header of each page to click that will bring you from one dashboard to another.

Corpus Progress Bar

---

mirrulations-dashboard/src/mirrdash/static/index.js
mirrulations-dashboard/src/mirrdash/templates/dev.html

Pull Request adds the Rabbitmq container status to the new dashboard in the /dev section

Adds RabbitMQ docker container status to new dashboard

---

mirrulations-dashboard/src/mirrdash/static/index.js

The numbers for comments and documents total were mixed up. Fixed and Ready to Merge

total comments and documents number were switched up

---

mirrulations-dashboard/src/mirrdash/static/index.js
mirrulations-dashboard/src/mirrdash/static/style.css
mirrulations-dashboard/src/mirrdash/templates/index.html

added numbers next to percents on dashboard

---

mirrulations-client/setup.cfg
mirrulations-client/src/mirrclient/client.py
mirrulations-client/src/mirrclient/saver.py
mirrulations-client/tests/test_saver.py
mirrulations-core/setup.cfg
mirrulations-core/src/mirrcore/amazon_s3.py
mirrulations-core/tests/test_amazon_s3.py

Client Rework for Downloading items to S3 directly

Client writes to S3

---

mirrulations-dashboard/src/mirrdash/dashboard_server.py
mirrulations-dashboard/src/mirrdash/static/index.js
mirrulations-dashboard/src/mirrdash/wsgi.py

https://github.com/MoravianUniversity/mirrulations/pull/130#issue-1663675105

fixes jobs_waiting and jobs_done percentages not adding up to 100

---

mirrulations-core/src/mirrcore/jobs_statistics.py
mirrulations-core/tests/test_job_statistics.py
mirrulations-dashboard/src/mirrdash/dashboard_server.py
mirrulations-dashboard/src/mirrdash/static/index.js
mirrulations-dashboard/tests/test_dashboard.py
mirrulations-work-generator/src/mirrgen/work_generator.py

Dynamic data totals for dashboard

---

docs/structure.md

Pull request contains an explanation of what this new data structure achieves, an example structure, and an explanation of the data structure

Created final structure explanation MD

---

mirrulations-dashboard/src/mirrdash/static/index.js
mirrulations-dashboard/src/mirrdash/templates/dev.html

I added the statuses of the extractor and the validator to the dev dashboard. This is ready to be merged.

Add extractor and validator to development dashboard

---

docs/TODO_extraction_queue.md

I am looking for a few people to read over this and decide whether any additional information should be added.

Add the .md file describing the new text extraction implementation using the ExtractionQueue

---

dev_setup.py
mirrulations-core/src/mirrcore/bucket_size.py
mirrulations-core/tests/test_bucket_size.py
mirrulations-work-generator/setup.cfg
mirrulations-work-generator/src/mirrgen/work_generator.py

Still need to specify the bucket or buckets and test

adding BucketSize class

---

docs/client.md
docs/production.md
docs/work_generator.md

This PR updates the `Client` and `Work Generator` documentation by providing better high and low level explanations of their functions.

Documentation Improvements

---

mirrulations-client/tests/test_client.py
mirrulations-core/src/mirrcore/path_generator.py
mirrulations-core/tests/test_path_generator.py

Modified the pathgenerator so that '/Raw_data' is prepended to each file path

made necessary changes to the pathgenerator.py file
